baseURL = "https://next.kevingimbel.de"
publishDir = "public"
[params]
    # Toggle "template hints" 
    # debug = true
    # Changes some templates. Indicates that this is a "next" deployment, e.g. future content or testing.
    is_next = true