baseURL = "https://kevingimbel.de"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "KevOps"
theme = ["hugo-atom-feed", "hugo-kg-shortcodes"]
publishDir = "docs"
# ignoreErrors = ["error-output-taxonomy"]

[params]
    # Doesn't work yet
    avatar_src = "images/general/mask-moshed.jpg"
    avatar_alt = "A colorful image of me wearing my DIY mask. The image has a colorful glitch effect."
    # Toggle "template hints" 
    # debug = true

[permalinks]
    blog = "/:section/:year/:month/:title/"
    photography = "/:section/:year/:month/:title/"
    projects = "/:section/:title/"
    art = "/:section/:year/:month/:title/"
    book = "/:section/:year/:title/"

[[params.now]]
location = "Wiesbaden, Germany"
    [[params.now.doing]]
    thing = "staying inside as much as possible."
    [[params.now.doing]]
    thing = "playing a lot of [No Man's Sky](https://www.nomanssky.com/) on PS4"
    [[params.now.doing]]
    thing = "starting and abondining lots of projects."

[menu]
    [[menu.main]]
    identifier = "home"
    name = "Home"
    URL = "/"
    Weight = 10

    [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20

    [[menu.main]]
    identifier = "blog"
    name = "Blog"
    URL = "/blog/"
    Weight = 30

    [[menu.main]]
    identifier = "project"
    name = "Projects"
    URL = "/project/"
    Weight = 35

    [[menu.main]]
    identifier = "photography"
    name = "Photography"
    URL = "/photography/"
    Weight = 40

    [[menu.main]]
    identifier = "reading"
    name = "Reading"
    URL = "/reading/"
    Weight = 45

    [[menu.main]]
    identifier = "Art"
    name = "Art"
    URL = "/art/"
    Weight = 50

    [[menu.main]]
    identifier = "Now"
    name = "Now"
    URL = "/now/"
    Weight = 60


[outputs]
    # <domain>/atom.xml
    home = ["HTML", "RSS", "ATOM"]     # default = ["HTML", "RSS"]
    # <domain>/posts/atom.xml
    section = ["HTML", "RSS", "ATOM"]  # default = ["HTML", "RSS"]

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[languages]
    [languages.en]
        weight = 1
        contentDir = "content/en"
        languageCode = "en_US"
        languageName = "English"
    [languages.de]
        weight = 2
        contentDir = "content/de"
        languageCode = "de_DE"
        languageName = "Deutsch"
    [languages.es]
        weight = 2
        contentDir = "content/es"
        languageCode = "es_ES"
        languageName = "Español"
    [languages.de.menu]
        [[languages.de.menu.main]]
        identifier = "start"
        name = "Start"
        URL = "/de/"
        Weight = 10

        [[languages.de.menu.main]]
        identifier = "ueber"
        name = "Über mich"
        url = "/de/ueber-mich/"
        weight = 20

        [[languages.de.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/de/blog"
        weight = 30


        [languages.de.params]
        # Doesn't work yet
        avatar_src = "images/general/mask-moshed.jpg"
        avatar_alt = "Ein Bild von mir mit meiner DIY Maske. Das Bild ist stark bearbeitet und hat einen Regenbogeneffekt"